# Generated by Django 4.1.1 on 2022-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
